### ISSUE TITLE
Citing this package

### ISSUE THREAD

**Issue by arnauqb** [francois-rozet/zuko#13]
This package has been very useful for my research and I would love to credit it. Would it be possible to create a Zenodo release to cite it properly? Thanks!

**Comment by francois-rozet** [comment]
Hello @arnauqb, I just created the Zenodo entry (see https://zenodo.org/record/7625672) and added a citation file in the repo :smiley: Thank you for your interest!

**Comment by arnauqb** [comment]
Thank you!
