### ISSUE TITLE
Allow vanilla `Transform` in `FlowModule`

### ISSUE THREAD

**Issue by felixdivo** [francois-rozet/zuko#15]
### Description

Using the library would be simpler if one could easily add existing transforms like `torch.distributions.ExpTransform()` like this:
```python
myflow.transforms.insert(0, ExpTransform())
```
or by directly passing them to the `FlowModule` constructor.

### Implementation

This initializer should accept more types:

https://github.com/francois-rozet/zuko/blob/4fba6620f06e771a98e01e980d621e9889858f73/zuko/flows.py#L80

One possibility would be to just do change this line:

https://github.com/francois-rozet/zuko/blob/4fba6620f06e771a98e01e980d621e9889858f73/zuko/flows.py#L97

to something like
```python
transform = ComposedTransform(*(
    # Only perform conditioning if we do not have a transform already
    t if isinstance(t, Transform) else t(y)
    for t in self.transforms
))
```

### Alternatives

One can wrap it into a `zuko.flows.Unconditional` as shown [here](https://github.com/francois-rozet/zuko/discussions/10#discussioncomment-4865555) or by using `zuko.flows.Unconditional(lambda _: transform)`, but this has several drawbacks:
1. If the `transform` has learnable parameters, they are not registered when calling `my_flow.parameters()`. This was my main pain point. You can register this in a separate and else unused attribute of the flow to circumvent this, but it feels more like a hack.
2. It bloats the code and is kind of unexpected to new users.
3. Dpending on how the callback is implemented, this might create many transforms that are not really needed to be re-created. I am unsure whether this is an actual perormance issue, but there are probably transforms that you do not want to re-create too often.

**Comment by francois-rozet** [comment]
Hello @felixdivo, thank you for the feature request. I think it is a great idea! The `transforms` attribute in `FlowModule` is and needs to be a `ModuleList`. So it cannot contain a transform which is not a module. I have three possible solutions:

1. We provide a dummy `TransformModule` sub-class that wraps an initialized `Transform`. The users are responsible for wrapping their transformations themselves.
2. We keep the dummy `TransformModule` sub-class, but wrap instances of `Transform` automatically inside the constructor of `FlowModule`.
3. We allow transformations that are sub-classes of both `Transform` and `Module` and skip the conditioning in `forward` of `FlowModule` if it is the case.

**Comment by felixdivo** [comment]
I see, the reason for the `ModuleList` makes sense.

> I think the second option is the easiest for users and also the most flexible.

Agreed. It might be a bit surprising if users dig into the `transforms` attribute but that's just how it is then.

Maybe it even makes sense for `TransformModule` to be private, since there is probably no instance where users should inherit from it or use it directly?

**Comment by francois-rozet** [comment]
Ok let's do that then. I'll make a PR.

However, could you give me an example of object that is both a `Transorm` and a `Module`. I am not sure how you handle the `__call__`.

> Maybe it even makes sense for TransformModule to be private

I like that `TranformModule` and `DistributionModule` are public abstract classes as they are the building blocks of Zuko.

**Comment by felixdivo** [comment]
> Maybe it even makes sense for `TransformModule` to be private, since there is probably no instance where users should inherit from it or use it directly?

Oh sorry, I meant the subclass of `TransformModule` that you want to add now. Not the `TransformModule` itself, which makes sense to have be public.

**Comment by felixdivo** [comment]
> Could you give me an example of object that is both a `Transorm` and a `Module`? I am not sure how you handle the `__call__`.

I guess [pyro](https://docs.pyro.ai/en/stable) has a few example of this, like all the transformations inheriting from [`TransformModule`](https://docs.pyro.ai/en/stable/distributions.html#transformmodule) or `ComposeTransformModule`. And I think you can just ignore `__call__()` and `forward()`, since the [base `Transform` already implements `__call__()`](https://github.com/pytorch/pytorch/blob/2ef66591076ee8984df97696d646ad4900f3924e/torch/distributions/transforms.py#L147-L158). And that's sufficient since it handles `transform_module(query)` calls and `transform_module.forward(query)` [should never be called directly anyways](https://pytorch.org/docs/stable/generated/torch.nn.Module.html#torch.nn.Module.forward).

**Comment by felixdivo** [comment]
Oh, and a concrete example of a transformation that would be a module at the same time would be a [`torch.distributions.transforms.AffineTransform`](https://pytorch.org/docs/stable/distributions.html#torch.distributions.transforms.AffineTransform) where you want to learn a parameter like `loc`. It would be really simple to have an `AffineTransform` that simply also inherits from `torch.nn.Module`, registers the parameters on itself and done.

**Comment by francois-rozet** [comment]
> I think you can just ignore __call__() and forward()

If you inherit from `Transform` and `Module`, you either lose the `__call__` of the former or the hooks of the latter.

> It would be really simple to have an `AffineTransform` that simply also inherits from `Module`

Wouldn't it need to rewrite the `__init__` function? Also, you should note that `scale` should never be equal to 0, which makes its optimization through SGD dangerous. For safety, one should constrain it (e.g. strictly positive) which requires it to be re-parametrized (`scale = exp(log_scale) + eps`).

> I think the second option is the easiest for users and also the most flexible.

One drawback about this option is that internal tensors of transformations will not be moved with the rest of the flow when calling `.to(device)` or `.cuda()`.

**Comment by francois-rozet** [comment]
Hello @felixdivo, although allowing plain transformations (`Transform`) in `FlowModule` would be convenient, I think it introduces too many complications, especially regarding internal tensors. I believe the current way to add plain transformations, that is using `zuko.flows.Unconditional`, is good enough.

I'll close this issue. Feel free to re-open it if you have a great idea.
